name: Deploy Documentation to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch_and_deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Download Documentation from GitLab
        env:
          GITLAB_PRIVATE_TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}
        run: |
          echo " Fetching latest artifact from GitLab..."
          
          GITLAB_PROJECT_ID="66"
          GITLAB_JOB_NAME="pages"
          ARTIFACT_URL="https://gitlab01.niryotech.com/api/v4/projects/66/jobs/39681/artifacts"
          # ARTIFACT_URL="https://gitlab01.niryotech.com/api/v4/projects/${GITLAB_PROJECT_ID}/jobs/artifacts/main/download?job=${GITLAB_JOB_NAME}"
          # Download the artifact from GitLab
          curl --location --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" --output artifact.zip "$ARTIFACT_URL"

          # Unzip artifact
          unzip artifact.zip
          rm artifact.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
