name: Deploy Documentation to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write

jobs:
  fetch_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
      - name: Download Documentation from GitLab
        env:
          GITLAB_PRIVATE_TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}
        run: |
          echo " Fetching latest artifact from GitLab..."
          
          GITLAB_PROJECT_ID="66"
          GITLAB_JOB_NAME="pages"
          ARTIFACT_URL="https://gitlab01.niryotech.com/api/v4/projects/${GITLAB_PROJECT_ID}/jobs/artifacts/main/download?job=${GITLAB_JOB_NAME}"

          # Download the artifact from GitLab
          curl --location --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" --output artifact.zip "$ARTIFACT_URL"

          # Unzip artifact
          unzip artifact.zip -d public/
          rm artifact.zip
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4